export enum PL_LABEL_STATUS {
  INITIALIZED = 'INITIALIZED',
  DOCUMENT_AWAITING = 'DOCUMENT_AWAITING',
  DOCUMENTATION_COMPLETE = 'DOCUMENTATION_COMPLETE',
  AUCTION = 'AUCTION',
  FUNDED = 'FUNDED',
  CONTRACT_AWAITING = 'CONTRACT_AWAITING',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  AWAITING_DISBURSEMENT = 'AWAITING_DISBURSEMENT',
  DISBURSED = 'DISBURSED',
  IN_REPAYMENT = 'IN_REPAYMENT',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  WITHDRAW = 'WITHDRAW',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  DISBURSEMENT = 'DISBURSEMENT',
  REJECT = 'REJECT',
  CANCEL = 'CANCEL',
  INFO = 'INFO',
  WORSE = 'WORSE',
}

export enum PL_MESSAGE_TYPE {
  SUCCESS = 'SUCCESS',
  INFORMATION = 'INFORMATION',
  WARNING = 'WARNING',
}
