name: Build & Deploy Production

on:
  push:
    branches: [ product ]

jobs:
  build-container:
    name: Build and Publish to Azure Container Registry
    runs-on: ubuntu-latest
    env:
      SVC_NAME: operator-svc
      ACR_NAME: ${{ secrets.CONTAINER_REGISTRY_HOST }}
      ENV_TYPE: production

    steps:
      - uses: AutoModality/action-clean@v1

      - uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: azure/docker-login@v1
        with:
         login-server: ${{ secrets.CONTAINER_REGISTRY_HOST }}
         username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
         password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build Container image
        run: docker build --build-arg ENV_TYPE=${ENV_TYPE} -t ${ACR_NAME}/${SVC_NAME}:product1.0 .

      - name: Publish Docker image
        run: docker push ${ACR_NAME}/${SVC_NAME}:product1.0

#  deploy:
#    name: Deploy to Digital Ocean K8s cluster
#    needs: build-container
#    runs-on: ubuntu-latest
#    env:
#      NAMESPACE: dev
#      SVC_NAME: customer-svc
#
#    steps:
#      - uses: Azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - uses: Azure/get-keyvault-secrets@v1.2
#        with:
#          keyvault: "monex-kv"
#          secrets: 'DEPLOYPAT, DIGITALOCEAN-ACCESS-TOKEN, DIGITALOCEAN-CLUSTER-NAME,  AWS-ACCESS-KEY-ID, AWS-SECRET-ACCESS-KEY'
#        id: getAzSecret
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ steps.getAzSecret.outputs.AWS-ACCESS-KEY-ID }}
#          aws-secret-access-key: ${{ steps.getAzSecret.outputs.AWS-SECRET-ACCESS-KEY }}
#          aws-region: 'ap-southeast-1'
#
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ steps.getAzSecret.outputs.DIGITALOCEAN-ACCESS-TOKEN }}
#
#      - name: Save DigitalOcean kubeconfig with short-lived credentials
#        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ steps.getAzSecret.outputs.DIGITALOCEAN-CLUSTER-NAME }}
#
#      - name: Install helm
#        uses: azure/setup-helm@v1
#        with:
#          version: v3.5.3 # default is latest stable
#        id: install
#
#      - name: Checkout helm-charts repo
#        uses: actions/checkout@v2
#        with:
#          repository: EpayVNTech/helm-charts
#          token: ${{ steps.getAzSecret.outputs.DEPLOYPAT }}
#
#      - name: Sops Binary Installer
#        uses: mdgreenwald/mozilla-sops-action@v1
#        with:
#          version: v3.7.1 # default is latest stable
#
#      - name: Decrypt config
#        run: |
#          sops -d ./configuration/${SVC_NAME}/${NAMESPACE}/app.enc.yaml > ./configuration/${SVC_NAME}/${NAMESPACE}/app.dec.yaml
#
#      - name: Deploy to DigitalOcean Kubernetes
#        run: |
#          helm upgrade ${SVC_NAME} ./charts/${SVC_NAME} --timeout 31m --install --wait --atomic -n ${NAMESPACE} \
#                --set app.name=${SVC_NAME} \
#                --set app.env=${NAMESPACE} \
#                --set app.namespace=${NAMESPACE} \
#                --set image.tag=latest \
#                --set autoscaling.maxReplicas=1 \
#                --set ingress.host=api-${NAMESPACE}.epay.vn \
#                --set ingress.secretName=api-${NAMESPACE}-tls \
#                --set-file configMap=./configuration/${SVC_NAME}/${NAMESPACE}/app.dec.yaml
#        timeout-minutes: 5
#
#      - name: Verify deployment
#        run: kubectl rollout status deployment/${SVC_NAME}-${NAMESPACE} -n ${NAMESPACE}
#        timeout-minutes: 5
